init:
  - git config --global core.autocrlf input

shallow_clone: true

version: '{build}'

skip_tags: true

install:
  - ps: Install-Product node 2
  - npm install --production
  - npm install tape

build: off

test_script:
  - node --harmony_arrow_functions test.js

cache:
  - node_modules
